name: unittest

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  submodules: true

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install uv
              run: pip install uv

            - name: Create and activate virtual environment
              run: |
                  uv venv .venv
                  source .venv/bin/activate
                  uv pip install -r pyproject.toml
                  uv pip install --extra dev -r pyproject.toml

            - name: Run tests
              run: |
                  source .venv/bin/activate
                  pytest
